server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_route2
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
            #            - After=2020-06-28T15:00:00.000+08:00[Asia/Shanghai]
            #            - Before=2020-06-28T15:05:00.000+08:00[Asia/Shanghai]
            #            - Between=2020-06-28T15:05:00.000+08:00[Asia/Shanghai], 2020-06-28T15:12:00.000+08:00[Asia/Shanghai]
            #            - Cookie=username, sitedev
            #            - Header=X-Request-Id, \d+
            #            - Host=**.sitedev.cn
            #            - Method=GET
            #            - Query=username, \d+
          filters:
            # 添加请求参数
            - AddRequestParameter=MyParameter, myParameter
            # 添加请求头
            - AddRequestHeader=MyHeader, myHeader
eureka:
  instance:
    hostname: cloud-gateway-service
  client: # 服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

